### ISSUE TITLE
Translation error when translating empty / unset components with relations

### ISSUE THREAD

**Issue by bbence84** [Fekide/strapi-plugin-deepl#12]
I am having the following issue: even though I have specified the following config:
      translateRelations: false,
and
      translatedFieldTypes: [
        'string',
        'text',
        'richtext'
      ],

I still get an error for a component related field:
message: "Cannot set properties of null (setting 'szallashely_kategoria')"

Even better would be that I could specify the exact fields (e.g. inside a specific content type) that should be translated.

Using the latest version (    "strapi-plugin-deepl": "^0.3.5")

Thanks!
Bence

**Comment by sargreal** [comment]
Hi @bbence84!

Thanks for reporting this issue :pray: 

Could you please provide a minimum failing example of the content type and the data of the source for translation? If you can't recreate it like that, you can also send me your actual content type and source via E-Mail.

Specifying exact fields will come at some point, probably in v0.4

**Comment by sargreal** [comment]
@bbence84 I have implemented a fix in #15 could you check if that works for you?

**Comment by bbence84** [comment]
> 

Thanks a lot! Sorry for the noob question, but how do I test a github version of an nmp package with strapi? Or will there be an official release soon? Thanks!

**Comment by sargreal** [comment]
@bbence84 

There is no general way to do it, but strapi allows local plugins, so you can put it there

- clone this repository to your `[strapi]/src/plugins` folder
- checkout branch `12-error-translating-empty-components-with-relations` (Make sure it actually uses the remote branch and not just a new branch from main. If you are not sure, you can do `git pull --set-upstream origin/12-error-translating-empty-components-with-relations` afterwards)
- add this line to your deepl plugin configuration (root level not inside `config`)
```js
module.exports = {
  // ...
  deepl: {
    // ...
    resolve: "./src/plugins/strapi-plugin-deepl", // path to plugin folder
    // ...
  },
  // ...
}
```
- (re)start strapi
