### ISSUE TITLE
Allow specifying for each field to be included in the translation or not

### ISSUE THREAD

**Issue by sargreal** [Fekide/strapi-plugin-deepl#13]
- [x] Add Configuration to Content-Type-Builder (Content-Type and Components)
      - Options: `translate`, `copy`, `delete`
      - Default: `translate` for all fields conforming to plugin config
      - Special handling for relations?
- [x] Filter fields `copy` and `delete` in `translatable-fields`
- [x] Add new method to remove fields with `delete` setting
- [x] Tests

**Comment by Slowl** [comment]
Hi !

I was wondering if this issue would fix the fact that today we can't specify which field can and can't be translated ?

My problem is that I have 2 `text` fields which needs to be excluded from the translation, but the only control we have today is to exclude **every** `text` fields from the translation

**Comment by sargreal** [comment]
@Slowl you can try version [v0.4.0-rc.1](https://github.com/Fekide/strapi-plugin-deepl/releases/tag/v0.4.0-rc.1)  for this feature,  please give any feedback!
