### ISSUE TITLE
JS error translations not working

### ISSUE THREAD

**Issue by cookiefirst** [Fekide/strapi-plugin-deepl#2]
I've been trying to get this plugin working, installing going well. The plugin is there and enabled, the fields appear in the editor. The copy function from other language does work but translation feature from a source language isn't. 

When I trigger a translation i get an console error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading ‘data’)
    at main.50a6bd34.js:2:1487884
    at c (main.50a6bd34.js:2:2132705)
    at Generator._invoke (main.50a6bd34.js:2:2132493)
    at Generator.next (main.50a6bd34.js:2:2133134)
    at t (main.50a6bd34.js:2:562)
    at u (main.50a6bd34.js:2:773)`

![Screenshot 2022-03-18 at 14 38 18](https://user-images.githubusercontent.com/93817342/159226421-f0b2f4f8-79cf-4075-bed6-9d9cc799326d.png)

I did run npm audit as well which returns:

`ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install strapi-plugin-deepl@0.1.2, which is a breaking change
node_modules/plop/node_modules/ora/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/plop/node_modules/ora/node_modules/strip-ansi
    ora  2.0.0 - 4.0.2
    Depends on vulnerable versions of strip-ansi
    node_modules/plop/node_modules/ora
      plop  2.2.0 - 2.7.6
      Depends on vulnerable versions of ora
      node_modules/plop
        @strapi/generators  *
        Depends on vulnerable versions of plop
        node_modules/@strapi/generators
          @strapi/plugin-content-type-builder  *
          Depends on vulnerable versions of @strapi/generators
          node_modules/@strapi/plugin-content-type-builder
          @strapi/strapi  *
          Depends on vulnerable versions of @strapi/generators
          node_modules/@strapi/strapi
            strapi-plugin-deepl  >=0.1.3
            Depends on vulnerable versions of @strapi/strapi
            node_modules/strapi-plugin-deepl`

Any ideas here on how to get it working?

**Comment by sargreal** [comment]
Just fixed it in adc263705c9e107a0e31aa6b2202420736dfbaf3 and the fix is also included in the new version (`0.3.3`) of the plugin.

The bug was that the function `formatComponentData` was renamed to `formatContentTypeData` in the strapi helper plugin in version `4.1.4`

**Comment by tomh4** [comment]
Hello,
now I am using Strapi 4.1.5 and I am getting the following error: 
`TypeError: (0 , r.formatContentTypeData) is not a function`

I assume it has something to do with this?

**Comment by tomh4** [comment]
@sargreal Please excuse my request, the Admin Panel did somehow not rebuild correctly, everything works now!

**Comment by rowphant** [comment]
Hello there,

Im using Strapi v4.1.3 and deepl plugin v0.3.5. Set up the config with free api key from the deepl account but I still get the same error as described in the first post. Any recommendations for solving this problem?

**Comment by anatolykopyl** [comment]
Same error as first message is present again in:
```json
"@strapi/strapi": "4.5.5",
"strapi-plugin-translate": "1.0.0",
"strapi-provider-translate-deepl": "1.0.0"
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
```

**Comment by anatolykopyl** [comment]
After further testing turns out that the error only appears if there is a "has one" relation field set to `translate`.

**Comment by sargreal** [comment]
@anatolykopyl can you please create a new issue for this, with minimal conten-type example?

**Comment by anatolykopyl** [comment]
@sargreal created issue #78
