### ISSUE TITLE
Every field populating: translated: Text

### ISSUE THREAD

**Issue by cookiefirst** [Fekide/strapi-plugin-deepl#3]
I updated the plugin, but it seems that everytime I try to do a translation it populates all fields with: "translated: Text" that's it. What could be the reason?

**Comment by cookiefirst** [comment]
If you issue the translate function which makes it fill in _translated:Text_ and then select the language dropdown it shows the other languages (including the source) as empty. 
<img width="1243" alt="Screenshot 2022-03-21 at 11 51 58" src="https://user-images.githubusercontent.com/93817342/159247039-bb38560c-8912-4233-bd9a-373e21a13686.png">

**Comment by sargreal** [comment]
Sorry, had some uncomitted code when publishing the package... :facepalm: 
Have pushed a new package 0.3.4

**Comment by sargreal** [comment]
About the second issue that you are reporting, please try with the new version again and open a new issue :)
