### ISSUE TITLE
Provider System

### ISSUE THREAD

**Issue by sargreal** [Fekide/strapi-plugin-deepl#30]
DeepL is not the only system that provides automated translation. And this plugin already includes a llot of code that would be duplicated in other translate apps

Maybe it would be a better approach to call the plugin `strapi-plugin-translate` and add providers like
- `strapi-provider-translate-deepl` or
- `strapi-provider-translate-google`

This provider system could also be used to support "manual translations" or external translation managers (see for example [@localazy/strapi-plugin](https://market.strapi.io/plugins/@localazy-strapi-plugin))

**Comment by sargreal** [comment]
@layaxx WDTY?
Should we do this? If yes, probably asap, so there are not more plugins created that basically copy all the functionalities?

**Comment by shawnvogt** [comment]
Hi @sargreal, I really like the provider system. 
Deepl does not support some of the languages I need to translate and this makes strapi-plugin-translate relevant to projects I work on whereas strapi-plugin-deepl would have been a starting point to make my own plugin. 

I don't really want to do that, I'd rather contribute here once I get my head wrapped around mono repos and how code is tested in this repo.

I have tweaked the deepl provider just enough to get it working with google cloud translate basic at [this repo](https://github.com/shawnvogt/strapi-provider-translate-gct). I'd be happy to open an issue and make a pr once I understand the testing and finish that part. 

Just thought I'd share early to show support for the change in direction to a provider system.

**Comment by sargreal** [comment]
@shawnvogt Thanks for your Input!

Yes that was exactly the plan. I had also seen your plugin on npm and thought now is definitely time to do this ^^

It is also my first time with monorepos, but it seemed like the best option here. 

Thanks for already implementing that, it looks very good already! I just merged the provider system into next, so you are free to open a merge request to the `next` branch already. I will be implementing the html <-> markdown part now, I am not sure how Google Could Translate is able to handle that, but I might need some input for you on that once I have the process ready

**Comment by sargreal** [comment]
Closing this since implementation merged into next
