### ISSUE TITLE
batch translation (needs to also 'translate' uids)

### ISSUE THREAD

**Issue by sargreal** [Fekide/strapi-plugin-deepl#6]
### Feature Description

Translate all or a specific list of entities of a content type to another locale. 

Requirements:
- Translation should happen in the background 
- Translation can be cancelled
- Current status can be requested
- Translation is paused on server shutdown and continued on start
- A failure in translation should stop the translation and the reason is saved
- Translation should not send too many requests to the DeepL-API
- User can configure if translated entities should be published directly or saved as draft if draftPublish feature is enabled

**Comment by tomh4** [comment]
Hello,
we are receiving 413 errors for large items, if the exceed the maximum size per request.
Will that be solved by the batching? Or is it for something else :) ?

**Comment by sargreal** [comment]
Hi @tomh4 

> we are receiving 413 errors for large items, if the exceed the maximum size per request.
> Will that be solved by the batching? Or is it for something else :) ?

No that is a different topic, this issue will handle translating multiple entities. Please open a separate issue for that :)

**Comment by tomh4** [comment]
Ah I see, sorry :)
