### ISSUE TITLE
DeepL 413 Error

### ISSUE THREAD

**Issue by tomh4** [Fekide/strapi-plugin-deepl#8]
With large translations, we are receiving a 413 error from DeepL, meaning the request size did exceed the allowed 128KiB
https://www.deepl.com/de/docs-api/accessing-the-api/limits/

Is there a way to split up translations into smaller requests? Maybe we can add a translate button to every single field, or have a selection dialog which fields should be translated?

**Comment by sargreal** [comment]
Selecting some fields to not be translated might be a cool feature, but I think for now the easiest solution would be to split the requests not just by number of fields but also by size.

See https://github.com/Fekide/strapi-plugin-deepl/blob/2c9b8aa8f6610bdbcd4ed6e2b58c077ff308bb67/server/utils/deepl-api.js#L33

This might however include a lot of tinkering since if one field itself is too big, it will need to be split as well.

**Comment by tomh4** [comment]
Hm I am actually not sure what part of my request causes the error, as it does not seem that big after all.
Is there a way to turn on logging of the requests? Maybe I can help with more details on the request

**Comment by sargreal** [comment]
@tomh4 

Not with some settings right now, but you can manually edit files in the node_modules folder. Just put this code into the file `node_modules/strapi-plugin-deepl/server/utils/deepl-api.js` after line 39 

```js
strapi.log.debug("Request: " + requestParams.toString())
strapi.log.debug("Length: " + requestParams.toString().length)
```

**Comment by jpizzati-uvl** [comment]
Is there a way to config the plugin to prevent certain keywords from being translated? @sargreal

**Comment by sargreal** [comment]
Hey @jpizzati-uvl 
Currently the only option is using the i18n plugin settings in the content-type builder  to set the field as “not translated” (See Advanced Settings for each field type in the [documentation on configuring fields](https://docs.strapi.io/user-docs/latest/content-types-builder/configuring-fields-content-type.html#regular-fields)

**Comment by sargreal** [comment]
@tomh4 Is the issue now actually connected to the amount of text or some other problem?

Error logs or using the approach in https://github.com/Fekide/strapi-plugin-deepl/issues/8#issuecomment-1086604410 would be very helpful

**Comment by tomh4** [comment]
Hello @sargreal , yes it is the length, here is the output:

{"expected":1235469,"length":1235469,"level":"error","limit":1048576,"message":"request entity too large","type":"entity.too.large"}

Maybe translating each field by itself would be an option?

**Comment by sargreal** [comment]
> {"expected":1235469,"length":1235469,"level":"error","limit":1048576,"message":"request entity too large","type":"entity.too.large"}

The numbers here are bits right?

**Comment by jpizzati-uvl** [comment]
> Hey @jpizzati-uvl Currently the only option is using the i18n plugin settings in the content-type builder to set the field as “not translated” (See Advanced Settings for each field type in the [documentation on configuring fields](https://docs.strapi.io/user-docs/latest/content-types-builder/configuring-fields-content-type.html#regular-fields) )

Thanks for the quick response!

**Comment by tomh4** [comment]
> > {"expected":1235469,"length":1235469,"level":"error","limit":1048576,"message":"request entity too large","type":"entity.too.large"}
> 
> The numbers here are bits right?

Yes I'd say so, this translates to the 128kb limit of deepl

**Comment by sargreal** [comment]
@tomh4 I have now finished on a fix in #11. Can you confirm that this works for you?

**Comment by tomh4** [comment]
@sargreal have you made a release yet? how can I test ?

**Comment by sargreal** [comment]
@tomh4 

- clone this repository to your `[strapi]/src/plugins` folder
- checkout branch `8-deepl-413-error`
- add this line to your deepl plugin configuration
```js
  deepl: {
    // ...
    resolve: "./src/plugins/strapi-plugin-deepl", // path to plugin folder
    // ...
  },
```
- (re)start strapi

**Comment by sargreal** [comment]
@tomh4 if you prefer a release, i can also make a beta release

**Comment by tomh4** [comment]
Alright i will do that, and get back to you soon!

**Comment by tomh4** [comment]
Hmm I did as you told, but I am still getting entity too large :(

**Comment by sargreal** [comment]
@tomh4 I have added some debug logging to the merge request. Can you confirm that these are happening and send the logs?

**Comment by tomh4** [comment]
Hmm i am not getting any logs, where should these show up?

**Comment by sargreal** [comment]
@tomh4 They should show up in the strapi server logs

So probably the plugin isn't resolved correctly

**Comment by tomh4** [comment]
I have removed the plugin from the package.json, then deleted the node_modules folder, and rebuild everything after adding it to the specified folder

**Comment by sargreal** [comment]
@tomh4 That's weird.. You are on the correct branch and pulled it right?

**Comment by tomh4** [comment]
yes..:/

**Comment by sargreal** [comment]
@tomh4 The log output should look something like this for your reference:
```
[2022-05-09 22:16:18.739] debug: DEEPL: Current chunk full with approx. 49197 bytes
[2022-05-09 22:16:18.740] debug: DEEPL: Current chunk full with approx. 50043 bytes
[2022-05-09 22:16:18.740] debug: DEEPL: Current chunk full with approx. 49197 bytes
[2022-05-09 22:16:18.740] debug: DEEPL: Last chunk size approx. 30195 bytes
[2022-05-09 22:16:18.741] debug: DEEPL: Last chunk size approx. 0 bytes
[2022-05-09 22:16:18.741] debug: DEEPL: Sending chunk of size 77 bytes
[2022-05-09 22:16:18.743] debug: DEEPL: Sending chunk of size 38271 bytes
[2022-05-09 22:16:18.745] debug: DEEPL: Sending chunk of size 38923 bytes
[2022-05-09 22:16:18.748] debug: DEEPL: Sending chunk of size 38271 bytes
[2022-05-09 22:16:18.751] debug: DEEPL: Sending chunk of size 23505 bytes
```

Can you do this and try once again?
```
git checkout 429e408d812149b9938cd64d32dff1438ed5815e
```
